<a href="https://colab.research.google.com/github/git2101487/DeepLearning2022Late/blob/main/NumPyReplay2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPyを使用する

In [1]:
import numpy as np

# 配列(アレイ)を作る

In [5]:
x = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
print(x)

x = np.array([1, 2, 3])
print(x)
print(type(x))

my_list1 = [1, 2, 3, 4, 5]
my_list1 = np.array(my_list1) # numpyのarrayを作る

my_list2 = [10, 20, 30, 40, 50]
my_lists = [my_list1, my_list2] # リストのリストを作る。
print(my_lists)

# my_listsを使ってNumPyのアレイを使る。(多次元配列を作る)
my_array2 = np.array(my_lists)

print(my_array2)

[1. 2. 3. 4. 5.]
[1 2 3]
<class 'numpy.ndarray'>
[array([1, 2, 3, 4, 5]), [10, 20, 30, 40, 50]]
[[ 1  2  3  4  5]
 [10 20 30 40 50]]


# NumPy配列の形状を調べる

In [4]:
a = np.array([1, 2, 3, 4])
print(a.shape)

b = np.array([[1, 2],[3, 4]])
b.shape

(4,)


(2, 2)

# 配列の生成 arange()

In [6]:
# 0から9までの数字(配列)を生成
x = np.arange(10)
print(x)

# reshape()は配列を形状に変換します 3×3の多次元配列
x = np.arange(1, 10).reshape(3, 3)
y = np.arange(1, 10).reshape(3, 3)

print(x)
print(y)

print(x + y)
print(x - y)
print(x * y)

[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


# 配列操作

In [7]:
sample_array = np.arange(10)
print(sample_array)

# reshapeを使って配列の形状を指定
sample_array2 = sample_array.reshape(2, 5)
print(sample_array2)

# concatenateを使って、データの結合する(axisで行方向か、縦方向を指定可能)
sample_array3 = np.array([[1, 2, 3], [4, 5, 6]])
sample_array4 = np.array([[7, 8, 9], [10, 11, 12]])

# 行方向に結合
print(np.concatenate([sample_array3, sample_array4], axis=1))

# hstackでも行方向の結合が可能
print(np.hstack((sample_array3, sample_array4)))

# axis=0で列方向 axis=1で行方向
print(np.concatenate([sample_array3, sample_array4], axis=0))

# vstackで列方向の結合が可能
print(np.vstack((sample_array3, sample_array4)))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# ブロードキャスト
### ブロードキャストは、配列の大きさが異なっていれば、自動的に要素をコピーし大きさを揃えるNumPyの機能です。

In [8]:
sample_array = np.arange(10)
print(sample_array)

# 上記の配列に「5」を足す計算
print(sample_array + 5)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


# 多次元配列の計算

In [9]:
n1 = np.array([1, 2, 3, 4, 5])
print(n1)

# 配列の次元数は np.ndim()関数で取得可能
print(np.ndim(n1))

# 配列の形状取得にはshapeを使う。タプルでかえってくる
print(n1.shape)

# 行(row) 配列の横方向 列(column) 配列の縦方向

n2 = np.array([[1, 2], [3, 4], [5 ,6]])
print(n2)

print(n2.ndim)

[1 2 3 4 5]
1
(5,)
[[1 2]
 [3 4]
 [5 6]]
2


# 行列とは
### 行列は、数や記号や式などを行と列に沿って配列したものです。
### 横のことを行／縦のことを列

In [10]:
my_li1 = [-1, 4]

my_li2 = [3, 2]

my_li3 = [2, 5]

my_li4 = [0, 1]

my_lists = [my_li1, my_li2, my_li3, my_li4]

my_array3 = np.array(my_lists)

print(my_array3)

[[-1  4]
 [ 3  2]
 [ 2  5]
 [ 0  1]]
