<a href="https://colab.research.google.com/github/git2101487/DeepLearning2022Late/blob/main/%E3%80%90%E8%AA%B2%E9%A1%8C%E3%80%91Iris_keras_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 穴埋め演習テスト問題

以下にあるのは、あやめ花（iris）のデータを分類するニューラルネットワーク処理のソースコードです。
以下の３つのパターンのいずれかの種類のあやめのサンプルデータが１レコードずつ収集されています。<br>
['setosa' 'versicolor' 'virginica']

各レコードの<br>
sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm) <br>
がくの長さ、幅、花びらの長さ、幅、<br>
のデータをもとにそれぞれがどの種類に該当するのかを分類・予測する学習モデルを作り、評価しています。

****のような連続アスタリスクでソースコードが隠されている部分を正常な命令文で置き換えて、すべてを正常に実行させて結果を表示させてください。 

## あやめデータをニューラルネットワークで分類する

### ライブラリのimport
tensorflowをtfとしてimportする 
numpyをnpとしてimportする
matplotlib.pyplotをpltとしてimportする

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

sklearnからdatasetsをimportする
sklearnからmodel_selectionをimportする

In [2]:
from sklearn import datasets
from sklearn import model_selection

In [3]:
# matplotlibのインライン宣言
%matplotlib inline
# あやめのデータセットを読み込み
iris = datasets.load_iris()
# irisの中身をprintする
print(iris)
# irisの特定の部分をprintする
print(iris.feature_names)
print(iris.target)
print(iris.target_names)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

### pandasという文字整形ライブラリでデータを見やすく表示

In [4]:
import pandas as pd
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target_names[iris.target]
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa  


### あやめデータをランダム(random_state=0)に並べ替えて、最初の20％をテスト用として(test_size)、残りを訓練用として分離する。
X_train:学習用データ
X_test:学習用の正解ラベルデータ
y_train:評価用データ
y_test:評価用ラベルデータ

In [5]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(
    iris.data, iris.target, test_size=0.2, random_state=0)

学習を実行

In [6]:
# kerasの学習モデルに層を設定
model = tf.keras.Sequential() # Sequential学習モデル
# 層を追加、出力4、活性化関数を「relu」関数に指定
model.add(tf.keras.layers.Dense(4, activation='relu'))
# 層を追加、出力3、活性化関数を「softmax」関数に指定
model.add(tf.keras.layers.Dense(3, activation='softmax'))

In [7]:
# 学習モデルをコンパイル、引数で以下を指定
# オプティマイザー=adam (損失をみて学習パラメータを更新する方法) 
3 # 損失関数=クロスエントロピー（正解率の計算方法）:sparse_categorical_crossentropy
# 指標 accuracy(正解率) 学習状況の監視の基準
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [8]:
# 学習を実行、第一引数は学習データ、第二引数は正解、エポック数を500に指定
model.fit(X_train, y_train, epochs=500)

Epoch 1/500


/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)


4/4 [==============================] - 1s 4ms/step - loss: 2.4313 - accuracy: 0.3250
Epoch 2/500
4/4 [==============================] - 0s 4ms/step - loss: 2.3608 - accuracy: 0.3250
Epoch 3/500
4/4 [==============================] - 0s 5ms/step - loss: 2.2952 - accuracy: 0.3250
Epoch 4/500
4/4 [==============================] - 0s 3ms/step - loss: 2.2333 - accuracy: 0.3250
Epoch 5/500
4/4 [==============================] - 0s 3ms/step - loss: 2.1719 - accuracy: 0.3250
Epoch 6/500
4/4 [==============================] - 0s 3ms/step - loss: 2.1153 - accuracy: 0.3250
Epoch 7/500
4/4 [==============================] - 0s 3ms/step - loss: 2.0585 - accuracy: 0.3250
Epoch 8/500
4/4 [==============================] - 0s 3ms/step - loss: 2.0066 - accuracy: 0.3250
Epoch 9/500
4/4 [==============================] - 0s 3ms/step - loss: 1.9546 - accuracy: 0.3250
Epoch 10/500
4/4 [==============================] - 0s 4ms/step - loss: 1.9078 - accuracy: 0.3250
Epoch 11/500
4/4 [=======================

学習済みのモデルを評価する

In [22]:
# 予測・推測させて結果を取得する
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])
predictions = probability_model.predict(X_test)
# それぞれ３パターンのうち一番高い確率を出した回答を抽出
pred = predictions.argmax(axis=1)
# 表示
# 正解を表示
print("正解\n",y_test)
# 予測を表示
print("予測\n",predictions)

1/1 [==============================] - 0s 64ms/step
正解
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
予測
 [[0.23136458 0.31115112 0.45748433]
 [0.2408961  0.35974675 0.3993572 ]
 [0.46739304 0.27741095 0.25519598]
 [0.22916509 0.30421942 0.4666155 ]
 [0.46739304 0.27741095 0.25519598]
 [0.2299818  0.3075089  0.46250927]
 [0.46739304 0.27741095 0.25519598]
 [0.23805927 0.35565454 0.40628624]
 [0.23569584 0.3448116  0.41949248]
 [0.24521495 0.36897096 0.38581407]
 [0.23281768 0.33385742 0.43332484]
 [0.24141629 0.366435   0.39214873]
 [0.23882203 0.36482793 0.39634997]
 [0.23697355 0.34727266 0.4157537 ]
 [0.23855571 0.3599064  0.4015379 ]
 [0.46739304 0.27741095 0.25519598]
 [0.23982514 0.35945466 0.40072015]
 [0.24129097 0.3685114  0.39019752]
 [0.46739304 0.27741095 0.25519598]
 [0.46739304 0.27741095 0.25519598]
 [0.2346782  0.33286685 0.432455  ]
 [0.24204086 0.36875027 0.38920885]
 [0.46383694 0.27949694 0.25666615]
 [0.46739304 0.27741095 0.25519598]
 [0.23494501 0

In [12]:
# 比較演算子結果のTrueは足し算に使うと1, Falseは0になる
# 各列ごとに比較した合計を問題数で割って正解率を表示
(pred == y_test).sum()/ len(pred)

0.6